# Generated by Django 3.2.9 on 2021-11-25 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_institute_names'),
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='application_job', to='jobboard.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='application_student', to='student.student')),
            ],
        ),
    ]
