# Generated by Django 3.2.9 on 2021-11-13 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.TextField(max_length=500)),
                ('company_website_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalInstitutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='auth.user')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U',
                                            max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('graduation_date', models.DateField()),
                ('educational_institute_name',
                 models.ManyToManyField(related_name='students', to='jobboard.EducationalInstitutes')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='auth.user')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U',
                                            max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('company_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recruiters',
                                   to='jobboard.company')),
            ],
        ),
    ]
