# Generated by Django 3.2.9 on 2021-11-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_add_example_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='work_from',
            field=models.CharField(choices=[('Office-Only', 'Office-Only'), ('Remote-Only', 'Remote-Only'), ('Hybrid', 'Hybrid')], default='Office_Only', max_length=255),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
