# Generated by Django 3.2.9 on 2021-11-25 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jobboard', '0002_add_example_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
