# Generated by Django 3.2.9 on 2021-11-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobboard', '0003_delete_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='work_from',
            field=models.CharField(
                choices=[('Office-Only', 'Office-Only'), ('Remote-Only', 'Remote-Only'), ('Hybrid', 'Hybrid')],
                default='Office_Only', max_length=255),
        ),
    ]
