# Generated by Django 3.2.9 on 2021-12-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0005_job_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='major',
            field=models.CharField(choices=[('U', 'Undecided'), ('CS', 'Computer Science'),
                                            ('SWE', 'Software Engineer'), ('EE', 'Electrical Engineer'),
                                            ('ME', 'Mechanical Engineer'), ('CE', 'Civil Engineer'),
                                            ('CHE', 'Chemical Engineer'), ('FI', 'Finance'), ('HR', 'Human Resources'),
                                            ('COM', 'Communications'), ('LAW', 'Law')], default='U', max_length=3),
        ),
    ]
