# Generated by Django 3.2.9 on 2021-11-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0002_institute_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(
                choices=[('U', 'Undecided'), ('CS', 'Computer Science'), ('SWE', 'Software Engineer'),
                         ('EE', 'Electrical Engineer'), ('ME', 'Mechanical Engineer'), ('CE', 'Civil Engineer'),
                         ('CHE', 'Chemical Engineer'), ('FI', 'Finance'), ('HR', 'Human Resources'),
                         ('COM', 'Communications'), ('LAW', 'Law')], default='U', max_length=3),
        ),
    ]
